name: Deploy PROD WEB

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  deployments: write
  id-token: write
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_web_eu:
    uses: ./.github/workflows/reusable-web-deploy.yml
    with:
      environment: production
      react_app_api_url: https://api.domain.com
      react_app_ws_url: https://ws.domain.com
      react_app_webhook_url: https://webhook.domain.com
      react_app_widget_embed_path: https://embed.domain.com/embed.umd.min.js
      react_app_sentry_dsn: https://2b5160da86384949be4cc66679c54e79@o1161119.ingest.sentry.io/6250907
      react_app_environment: production
      react_app_mail_server_domain: inbound-mail.domain.com
      react_app_hubspot_embed: 44416662
      netlify_deploy_message: Prod deployment
      netlify_alias: prod
      netlify_gh_env: Production
      netlify_site_id: d2e8b860-7016-4202-9256-ebca0f13259a
      clerk_publishable_key: pk_live_Y2xlcmsuZXUuZGFzaGJvYXJkLm5vdnUuY28k
      clerk_is_ee_auth_enabled: true
      new_dashboard_url: https://dashboard-v2.domain.com
    secrets: inherit
